// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: models.proto
// Protobuf C++ Version: 5.28.2

#include "models.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace models {

inline constexpr InitResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : error_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR InitResponse::InitResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct InitResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InitResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InitResponseDefaultTypeInternal() {}
  union {
    InitResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InitResponseDefaultTypeInternal _InitResponse_default_instance_;

inline constexpr InitRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : project_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR InitRequest::InitRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct InitRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InitRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InitRequestDefaultTypeInternal() {}
  union {
    InitRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InitRequestDefaultTypeInternal _InitRequest_default_instance_;

inline constexpr GetattrRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : path_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetattrRequest::GetattrRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetattrRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetattrRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetattrRequestDefaultTypeInternal() {}
  union {
    GetattrRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetattrRequestDefaultTypeInternal _GetattrRequest_default_instance_;

inline constexpr GetattrResponse_stat::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        mtime_{nullptr},
        size_{::int64_t{0}},
        mode_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetattrResponse_stat::GetattrResponse_stat(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetattrResponse_statDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetattrResponse_statDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetattrResponse_statDefaultTypeInternal() {}
  union {
    GetattrResponse_stat _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetattrResponse_statDefaultTypeInternal _GetattrResponse_stat_default_instance_;

inline constexpr GetattrResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        stbuf_{nullptr},
        error_{0},
        result_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetattrResponse::GetattrResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetattrResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetattrResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetattrResponseDefaultTypeInternal() {}
  union {
    GetattrResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetattrResponseDefaultTypeInternal _GetattrResponse_default_instance_;
}  // namespace models
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_models_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_models_2eproto = nullptr;
const ::uint32_t
    TableStruct_models_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::models::InitRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::models::InitRequest, _impl_.project_name_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::models::InitResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::models::InitResponse, _impl_.error_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::models::GetattrRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::models::GetattrRequest, _impl_.path_),
        PROTOBUF_FIELD_OFFSET(::models::GetattrResponse_stat, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::models::GetattrResponse_stat, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::models::GetattrResponse_stat, _impl_.mode_),
        PROTOBUF_FIELD_OFFSET(::models::GetattrResponse_stat, _impl_.size_),
        PROTOBUF_FIELD_OFFSET(::models::GetattrResponse_stat, _impl_.mtime_),
        ~0u,
        ~0u,
        0,
        PROTOBUF_FIELD_OFFSET(::models::GetattrResponse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::models::GetattrResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::models::GetattrResponse, _impl_.error_),
        PROTOBUF_FIELD_OFFSET(::models::GetattrResponse, _impl_.stbuf_),
        PROTOBUF_FIELD_OFFSET(::models::GetattrResponse, _impl_.result_),
        ~0u,
        0,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::models::InitRequest)},
        {9, -1, -1, sizeof(::models::InitResponse)},
        {18, -1, -1, sizeof(::models::GetattrRequest)},
        {27, 38, -1, sizeof(::models::GetattrResponse_stat)},
        {41, 52, -1, sizeof(::models::GetattrResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::models::_InitRequest_default_instance_._instance,
    &::models::_InitResponse_default_instance_._instance,
    &::models::_GetattrRequest_default_instance_._instance,
    &::models::_GetattrResponse_stat_default_instance_._instance,
    &::models::_GetattrResponse_default_instance_._instance,
};
const char descriptor_table_protodef_models_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014models.proto\022\006models\032\031google/protobuf/"
    "any.proto\032\037google/protobuf/timestamp.pro"
    "to\"#\n\013InitRequest\022\024\n\014project_name\030\001 \001(\t\""
    "\035\n\014InitResponse\022\r\n\005error\030\001 \001(\005\"\036\n\016Getatt"
    "rRequest\022\014\n\004path\030\001 \001(\t\"\254\001\n\017GetattrRespon"
    "se\022\r\n\005error\030\001 \001(\005\022+\n\005stbuf\030\002 \001(\0132\034.model"
    "s.GetattrResponse.stat\022\016\n\006result\030\003 \001(\005\032M"
    "\n\004stat\022\014\n\004mode\030\001 \001(\005\022\014\n\004size\030\002 \001(\003\022)\n\005mt"
    "ime\030\003 \001(\0132\032.google.protobuf.Timestamp*\\\n"
    "\nPacketType\022\020\n\014INIT_REQUEST\020\000\022\021\n\rINIT_RE"
    "SPONSE\020\001\022\023\n\017GETATTR_REQUEST\020\002\022\024\n\020GETATTR"
    "_RESPONSE\020\003B\tZ\007models/b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_models_2eproto_deps[2] =
    {
        &::descriptor_table_google_2fprotobuf_2fany_2eproto,
        &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::absl::once_flag descriptor_table_models_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_models_2eproto = {
    false,
    false,
    470,
    descriptor_table_protodef_models_2eproto,
    "models.proto",
    &descriptor_table_models_2eproto_once,
    descriptor_table_models_2eproto_deps,
    2,
    5,
    schemas,
    file_default_instances,
    TableStruct_models_2eproto::offsets,
    file_level_enum_descriptors_models_2eproto,
    file_level_service_descriptors_models_2eproto,
};
namespace models {
const ::google::protobuf::EnumDescriptor* PacketType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_models_2eproto);
  return file_level_enum_descriptors_models_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t PacketType_internal_data_[] = {
    262144u, 0u, };
bool PacketType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
// ===================================================================

class InitRequest::_Internal {
 public:
};

InitRequest::InitRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:models.InitRequest)
}
inline PROTOBUF_NDEBUG_INLINE InitRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::models::InitRequest& from_msg)
      : project_name_(arena, from.project_name_),
        _cached_size_{0} {}

InitRequest::InitRequest(
    ::google::protobuf::Arena* arena,
    const InitRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  InitRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:models.InitRequest)
}
inline PROTOBUF_NDEBUG_INLINE InitRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : project_name_(arena),
        _cached_size_{0} {}

inline void InitRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
InitRequest::~InitRequest() {
  // @@protoc_insertion_point(destructor:models.InitRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void InitRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.project_name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    InitRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_InitRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &InitRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<InitRequest>(),
            ::google::protobuf::Message::GetNewImpl<InitRequest>(),
            ::google::protobuf::Message::GetClearImpl<InitRequest>(), &InitRequest::ByteSizeLong,
                &InitRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(InitRequest, _impl_._cached_size_),
            false,
        },
        &InitRequest::kDescriptorMethods,
        &descriptor_table_models_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* InitRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 39, 2> InitRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::models::InitRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string project_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(InitRequest, _impl_.project_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string project_name = 1;
    {PROTOBUF_FIELD_OFFSET(InitRequest, _impl_.project_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\14\0\0\0\0\0\0"
    "models.InitRequest"
    "project_name"
  }},
};

PROTOBUF_NOINLINE void InitRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:models.InitRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.project_name_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* InitRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const InitRequest& this_ = static_cast<const InitRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* InitRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const InitRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:models.InitRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string project_name = 1;
          if (!this_._internal_project_name().empty()) {
            const std::string& _s = this_._internal_project_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "models.InitRequest.project_name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:models.InitRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t InitRequest::ByteSizeLong(const MessageLite& base) {
          const InitRequest& this_ = static_cast<const InitRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t InitRequest::ByteSizeLong() const {
          const InitRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:models.InitRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string project_name = 1;
            if (!this_._internal_project_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_project_name());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void InitRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<InitRequest*>(&to_msg);
  auto& from = static_cast<const InitRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:models.InitRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_project_name().empty()) {
    _this->_internal_set_project_name(from._internal_project_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void InitRequest::CopyFrom(const InitRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:models.InitRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void InitRequest::InternalSwap(InitRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.project_name_, &other->_impl_.project_name_, arena);
}

::google::protobuf::Metadata InitRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class InitResponse::_Internal {
 public:
};

InitResponse::InitResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:models.InitResponse)
}
InitResponse::InitResponse(
    ::google::protobuf::Arena* arena, const InitResponse& from)
    : InitResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE InitResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void InitResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.error_ = {};
}
InitResponse::~InitResponse() {
  // @@protoc_insertion_point(destructor:models.InitResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void InitResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    InitResponse::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_InitResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &InitResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<InitResponse>(),
            ::google::protobuf::Message::GetNewImpl<InitResponse>(),
            ::google::protobuf::Message::GetClearImpl<InitResponse>(), &InitResponse::ByteSizeLong,
                &InitResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(InitResponse, _impl_._cached_size_),
            false,
        },
        &InitResponse::kDescriptorMethods,
        &descriptor_table_models_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* InitResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> InitResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::models::InitResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 error = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(InitResponse, _impl_.error_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(InitResponse, _impl_.error_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 error = 1;
    {PROTOBUF_FIELD_OFFSET(InitResponse, _impl_.error_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void InitResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:models.InitResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* InitResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const InitResponse& this_ = static_cast<const InitResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* InitResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const InitResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:models.InitResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 error = 1;
          if (this_._internal_error() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_error(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:models.InitResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t InitResponse::ByteSizeLong(const MessageLite& base) {
          const InitResponse& this_ = static_cast<const InitResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t InitResponse::ByteSizeLong() const {
          const InitResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:models.InitResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 error = 1;
            if (this_._internal_error() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_error());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void InitResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<InitResponse*>(&to_msg);
  auto& from = static_cast<const InitResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:models.InitResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_error() != 0) {
    _this->_impl_.error_ = from._impl_.error_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void InitResponse::CopyFrom(const InitResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:models.InitResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void InitResponse::InternalSwap(InitResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.error_, other->_impl_.error_);
}

::google::protobuf::Metadata InitResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetattrRequest::_Internal {
 public:
};

GetattrRequest::GetattrRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:models.GetattrRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetattrRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::models::GetattrRequest& from_msg)
      : path_(arena, from.path_),
        _cached_size_{0} {}

GetattrRequest::GetattrRequest(
    ::google::protobuf::Arena* arena,
    const GetattrRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetattrRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:models.GetattrRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetattrRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : path_(arena),
        _cached_size_{0} {}

inline void GetattrRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetattrRequest::~GetattrRequest() {
  // @@protoc_insertion_point(destructor:models.GetattrRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetattrRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.path_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetattrRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_GetattrRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetattrRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<GetattrRequest>(),
            ::google::protobuf::Message::GetNewImpl<GetattrRequest>(),
            ::google::protobuf::Message::GetClearImpl<GetattrRequest>(), &GetattrRequest::ByteSizeLong,
                &GetattrRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetattrRequest, _impl_._cached_size_),
            false,
        },
        &GetattrRequest::kDescriptorMethods,
        &descriptor_table_models_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetattrRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 34, 2> GetattrRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::models::GetattrRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string path = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetattrRequest, _impl_.path_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string path = 1;
    {PROTOBUF_FIELD_OFFSET(GetattrRequest, _impl_.path_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\25\4\0\0\0\0\0\0"
    "models.GetattrRequest"
    "path"
  }},
};

PROTOBUF_NOINLINE void GetattrRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:models.GetattrRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.path_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetattrRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetattrRequest& this_ = static_cast<const GetattrRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetattrRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetattrRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:models.GetattrRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string path = 1;
          if (!this_._internal_path().empty()) {
            const std::string& _s = this_._internal_path();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "models.GetattrRequest.path");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:models.GetattrRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetattrRequest::ByteSizeLong(const MessageLite& base) {
          const GetattrRequest& this_ = static_cast<const GetattrRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetattrRequest::ByteSizeLong() const {
          const GetattrRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:models.GetattrRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string path = 1;
            if (!this_._internal_path().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_path());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetattrRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetattrRequest*>(&to_msg);
  auto& from = static_cast<const GetattrRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:models.GetattrRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_path().empty()) {
    _this->_internal_set_path(from._internal_path());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetattrRequest::CopyFrom(const GetattrRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:models.GetattrRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetattrRequest::InternalSwap(GetattrRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.path_, &other->_impl_.path_, arena);
}

::google::protobuf::Metadata GetattrRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetattrResponse_stat::_Internal {
 public:
  using HasBits =
      decltype(std::declval<GetattrResponse_stat>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GetattrResponse_stat, _impl_._has_bits_);
};

void GetattrResponse_stat::clear_mtime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.mtime_ != nullptr) _impl_.mtime_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
GetattrResponse_stat::GetattrResponse_stat(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:models.GetattrResponse.stat)
}
inline PROTOBUF_NDEBUG_INLINE GetattrResponse_stat::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::models::GetattrResponse_stat& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

GetattrResponse_stat::GetattrResponse_stat(
    ::google::protobuf::Arena* arena,
    const GetattrResponse_stat& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetattrResponse_stat* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.mtime_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(
                              arena, *from._impl_.mtime_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, size_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, size_),
           offsetof(Impl_, mode_) -
               offsetof(Impl_, size_) +
               sizeof(Impl_::mode_));

  // @@protoc_insertion_point(copy_constructor:models.GetattrResponse.stat)
}
inline PROTOBUF_NDEBUG_INLINE GetattrResponse_stat::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GetattrResponse_stat::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, mtime_),
           0,
           offsetof(Impl_, mode_) -
               offsetof(Impl_, mtime_) +
               sizeof(Impl_::mode_));
}
GetattrResponse_stat::~GetattrResponse_stat() {
  // @@protoc_insertion_point(destructor:models.GetattrResponse.stat)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetattrResponse_stat::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.mtime_;
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetattrResponse_stat::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_GetattrResponse_stat_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetattrResponse_stat::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<GetattrResponse_stat>(),
            ::google::protobuf::Message::GetNewImpl<GetattrResponse_stat>(),
            ::google::protobuf::Message::GetClearImpl<GetattrResponse_stat>(), &GetattrResponse_stat::ByteSizeLong,
                &GetattrResponse_stat::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetattrResponse_stat, _impl_._cached_size_),
            false,
        },
        &GetattrResponse_stat::kDescriptorMethods,
        &descriptor_table_models_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetattrResponse_stat::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2> GetattrResponse_stat::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GetattrResponse_stat, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::models::GetattrResponse_stat>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 mode = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GetattrResponse_stat, _impl_.mode_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GetattrResponse_stat, _impl_.mode_)}},
    // int64 size = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(GetattrResponse_stat, _impl_.size_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(GetattrResponse_stat, _impl_.size_)}},
    // .google.protobuf.Timestamp mtime = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(GetattrResponse_stat, _impl_.mtime_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 mode = 1;
    {PROTOBUF_FIELD_OFFSET(GetattrResponse_stat, _impl_.mode_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int64 size = 2;
    {PROTOBUF_FIELD_OFFSET(GetattrResponse_stat, _impl_.size_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // .google.protobuf.Timestamp mtime = 3;
    {PROTOBUF_FIELD_OFFSET(GetattrResponse_stat, _impl_.mtime_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void GetattrResponse_stat::Clear() {
// @@protoc_insertion_point(message_clear_start:models.GetattrResponse.stat)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.mtime_ != nullptr);
    _impl_.mtime_->Clear();
  }
  ::memset(&_impl_.size_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.mode_) -
      reinterpret_cast<char*>(&_impl_.size_)) + sizeof(_impl_.mode_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetattrResponse_stat::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetattrResponse_stat& this_ = static_cast<const GetattrResponse_stat&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetattrResponse_stat::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetattrResponse_stat& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:models.GetattrResponse.stat)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 mode = 1;
          if (this_._internal_mode() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_mode(), target);
          }

          // int64 size = 2;
          if (this_._internal_size() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<2>(
                    stream, this_._internal_size(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .google.protobuf.Timestamp mtime = 3;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                3, *this_._impl_.mtime_, this_._impl_.mtime_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:models.GetattrResponse.stat)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetattrResponse_stat::ByteSizeLong(const MessageLite& base) {
          const GetattrResponse_stat& this_ = static_cast<const GetattrResponse_stat&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetattrResponse_stat::ByteSizeLong() const {
          const GetattrResponse_stat& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:models.GetattrResponse.stat)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .google.protobuf.Timestamp mtime = 3;
            cached_has_bits =
                this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.mtime_);
            }
          }
           {
            // int64 size = 2;
            if (this_._internal_size() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_size());
            }
            // int32 mode = 1;
            if (this_._internal_mode() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_mode());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetattrResponse_stat::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetattrResponse_stat*>(&to_msg);
  auto& from = static_cast<const GetattrResponse_stat&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:models.GetattrResponse.stat)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.mtime_ != nullptr);
    if (_this->_impl_.mtime_ == nullptr) {
      _this->_impl_.mtime_ =
          ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(arena, *from._impl_.mtime_);
    } else {
      _this->_impl_.mtime_->MergeFrom(*from._impl_.mtime_);
    }
  }
  if (from._internal_size() != 0) {
    _this->_impl_.size_ = from._impl_.size_;
  }
  if (from._internal_mode() != 0) {
    _this->_impl_.mode_ = from._impl_.mode_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetattrResponse_stat::CopyFrom(const GetattrResponse_stat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:models.GetattrResponse.stat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetattrResponse_stat::InternalSwap(GetattrResponse_stat* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GetattrResponse_stat, _impl_.mode_)
      + sizeof(GetattrResponse_stat::_impl_.mode_)
      - PROTOBUF_FIELD_OFFSET(GetattrResponse_stat, _impl_.mtime_)>(
          reinterpret_cast<char*>(&_impl_.mtime_),
          reinterpret_cast<char*>(&other->_impl_.mtime_));
}

::google::protobuf::Metadata GetattrResponse_stat::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetattrResponse::_Internal {
 public:
  using HasBits =
      decltype(std::declval<GetattrResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GetattrResponse, _impl_._has_bits_);
};

GetattrResponse::GetattrResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:models.GetattrResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetattrResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::models::GetattrResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

GetattrResponse::GetattrResponse(
    ::google::protobuf::Arena* arena,
    const GetattrResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetattrResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.stbuf_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::models::GetattrResponse_stat>(
                              arena, *from._impl_.stbuf_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, error_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, error_),
           offsetof(Impl_, result_) -
               offsetof(Impl_, error_) +
               sizeof(Impl_::result_));

  // @@protoc_insertion_point(copy_constructor:models.GetattrResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetattrResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GetattrResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, stbuf_),
           0,
           offsetof(Impl_, result_) -
               offsetof(Impl_, stbuf_) +
               sizeof(Impl_::result_));
}
GetattrResponse::~GetattrResponse() {
  // @@protoc_insertion_point(destructor:models.GetattrResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetattrResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.stbuf_;
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetattrResponse::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_GetattrResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetattrResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<GetattrResponse>(),
            ::google::protobuf::Message::GetNewImpl<GetattrResponse>(),
            ::google::protobuf::Message::GetClearImpl<GetattrResponse>(), &GetattrResponse::ByteSizeLong,
                &GetattrResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetattrResponse, _impl_._cached_size_),
            false,
        },
        &GetattrResponse::kDescriptorMethods,
        &descriptor_table_models_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetattrResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2> GetattrResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GetattrResponse, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::models::GetattrResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 error = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GetattrResponse, _impl_.error_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GetattrResponse, _impl_.error_)}},
    // .models.GetattrResponse.stat stbuf = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(GetattrResponse, _impl_.stbuf_)}},
    // int32 result = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GetattrResponse, _impl_.result_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(GetattrResponse, _impl_.result_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 error = 1;
    {PROTOBUF_FIELD_OFFSET(GetattrResponse, _impl_.error_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .models.GetattrResponse.stat stbuf = 2;
    {PROTOBUF_FIELD_OFFSET(GetattrResponse, _impl_.stbuf_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // int32 result = 3;
    {PROTOBUF_FIELD_OFFSET(GetattrResponse, _impl_.result_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }}, {{
    {::_pbi::TcParser::GetTable<::models::GetattrResponse_stat>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void GetattrResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:models.GetattrResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.stbuf_ != nullptr);
    _impl_.stbuf_->Clear();
  }
  ::memset(&_impl_.error_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.result_) -
      reinterpret_cast<char*>(&_impl_.error_)) + sizeof(_impl_.result_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetattrResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetattrResponse& this_ = static_cast<const GetattrResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetattrResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetattrResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:models.GetattrResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 error = 1;
          if (this_._internal_error() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_error(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .models.GetattrResponse.stat stbuf = 2;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.stbuf_, this_._impl_.stbuf_->GetCachedSize(), target,
                stream);
          }

          // int32 result = 3;
          if (this_._internal_result() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_result(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:models.GetattrResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetattrResponse::ByteSizeLong(const MessageLite& base) {
          const GetattrResponse& this_ = static_cast<const GetattrResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetattrResponse::ByteSizeLong() const {
          const GetattrResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:models.GetattrResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .models.GetattrResponse.stat stbuf = 2;
            cached_has_bits =
                this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.stbuf_);
            }
          }
           {
            // int32 error = 1;
            if (this_._internal_error() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_error());
            }
            // int32 result = 3;
            if (this_._internal_result() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_result());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetattrResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetattrResponse*>(&to_msg);
  auto& from = static_cast<const GetattrResponse&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:models.GetattrResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.stbuf_ != nullptr);
    if (_this->_impl_.stbuf_ == nullptr) {
      _this->_impl_.stbuf_ =
          ::google::protobuf::Message::CopyConstruct<::models::GetattrResponse_stat>(arena, *from._impl_.stbuf_);
    } else {
      _this->_impl_.stbuf_->MergeFrom(*from._impl_.stbuf_);
    }
  }
  if (from._internal_error() != 0) {
    _this->_impl_.error_ = from._impl_.error_;
  }
  if (from._internal_result() != 0) {
    _this->_impl_.result_ = from._impl_.result_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetattrResponse::CopyFrom(const GetattrResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:models.GetattrResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetattrResponse::InternalSwap(GetattrResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GetattrResponse, _impl_.result_)
      + sizeof(GetattrResponse::_impl_.result_)
      - PROTOBUF_FIELD_OFFSET(GetattrResponse, _impl_.stbuf_)>(
          reinterpret_cast<char*>(&_impl_.stbuf_),
          reinterpret_cast<char*>(&other->_impl_.stbuf_));
}

::google::protobuf::Metadata GetattrResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace models
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_models_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
